POST http://localhost:8011
content-type: application/json

{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "eth_blockNumber",
    "params": []
}

###

POST http://localhost:8011
content-type: application/json

{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "eth_gasPrice",
    "params": []
}

###
POST http://localhost:8011
content-type: application/json

{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "net_version",
    "params": []
}

###
POST http://localhost:8011
content-type: application/json

{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "net_listening",
    "params": []
}

###
POST http://localhost:8011
content-type: application/json

{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "net_peerCount",
    "params": []
}

###
POST http://localhost:8011
content-type: application/json

{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "config_getShowCalls",
    "params": []
}

###
POST http://localhost:8011
content-type: application/json

{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "config_setShowCalls",
    "params": ["All"]
}

###
POST http://localhost:8011
content-type: application/json

{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "config_setShowStorageLogs",
    "params": ["All"]
}

###
POST http://localhost:8011
content-type: application/json

{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "config_setShowVmDetails",
    "params": ["All"]
}

###
POST http://localhost:8011
content-type: application/json

{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "config_setShowGasDetails",
    "params": ["All"]
}

###
POST http://localhost:8011
content-type: application/json

{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "config_setResolveHashes",
    "params": [true]
}

###
POST http://localhost:8011
content-type: application/json

{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "eth_chainId",
    "params": []
}

###
POST http://localhost:8011
content-type: application/json

{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "eth_estimateGas",
    "params": [{
        "0x0000000000000000000000000000000000000000": true
    }]
}

###
POST http://localhost:8011
content-type: application/json

{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "eth_gasPrice",
    "params": []
}

###
POST http://localhost:8011
content-type: application/json

{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "eth_getBalance",
    "params": ["0x0000000000000000000000000000000000000000", "latest"]
}

###
POST http://localhost:8011
content-type: application/json

{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "eth_getBlockByHash",
    "params": ["0x0000000000000000000000000000000000000000000000000000000000000000", true]
}

###
POST http://localhost:8011
content-type: application/json

{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "eth_getBlockByNumber",
    "params": ["latest", true]
}

###
POST http://localhost:8011
content-type: application/json

{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "eth_getCode",
    "params": ["0x0000000000000000000000000000000000000000", "latest"]
}

###
POST http://localhost:8011
content-type: application/json

{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "eth_getTransactionByHash",
    "params": ["0x0000000000000000000000000000000000000000000000000000000000000000"]
}

###
POST http://localhost:8011
content-type: application/json

{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "eth_getTransactionCount",
    "params": ["0x0000000000000000000000000000000000000000", "latest"]
}

###
POST http://localhost:8011
content-type: application/json

{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "eth_sendRawTransaction",
    "params": ["0x0000"]
}

###
POST http://localhost:8011
content-type: application/json

{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "eth_blockNumber",
    "params": []
}

###
POST http://localhost:8011
content-type: application/json

{
    "jsonrpc": "2.0",
    "id": "2",
    "method": "eth_call",
    "params": [{
        "to": "0x36615Cf349d7F6344891B1e7CA7C72883F5dc049",
        "data": "0x0000",
        "from": "0xa61464658AfeAf65CccaaFD3a512b69A83B77618",
        "gas": "0x0000",
        "gasPrice": "0x0000",
        "value": "0x0000",
        "nonce": "0x0000"
    }, "latest"]
}

###
POST http://localhost:8011
content-type: application/json

{
    "jsonrpc": "2.0",
    "id": "2",
    "method": "eth_syncing",
    "params": []
}

###
POST http://localhost:8011
content-type: application/json

{
    "jsonrpc": "2.0",
    "id": "2",
    "method": "evm_increaseTime",
    "params": [10]
}

###
POST http://localhost:8011
content-type: application/json

{
    "jsonrpc": "2.0",
    "id": "2",
    "method": "evm_setNextBlockTimestamp",
    "params": [1672527600]
}

###
POST http://localhost:8011
content-type: application/json

{
    "jsonrpc": "2.0",
    "id": "2",
    "method": "evm_setTime",
    "params": [1672527600]
}

###
POST http://localhost:8011
content-type: application/json

{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "evm_mine",
    "params": []
}

###
POST http://localhost:8011
content-type: application/json

{
    "jsonrpc": "2.0",
    "id": "2",
    "method": "eth_getBlockByHash",
    "params": ["0x371c9871792d89fea30e6b947ca45e9798e4f577dcdddb79269a93450f52b459", true]
}


###
POST http://localhost:8011
content-type: application/json

{
    "jsonrpc": "2.0",
    "id": "2",
    "method": "eth_getBlockByNumber",
    "params": ["0xc9d5bb", false]
}

###
POST http://localhost:8011
content-type: application/json

{
    "jsonrpc": "2.0",
    "id": "2",
    "method": "eth_getBlockByNumber",
    "params": ["latest", false]
}

###
POST http://localhost:8011
content-type: application/json

{
    "jsonrpc": "2.0",
    "id": "2",
    "method": "eth_getBlockByNumber",
    "params": ["earliest", false]
}

###
POST http://localhost:8011
content-type: application/json

{
    "jsonrpc": "2.0",
    "id": "2",
    "method": "eth_getBlockTransactionCountByHash",
    "params": ["0x371c9871792d89fea30e6b947ca45e9798e4f577dcdddb79269a93450f52b459"]
}


###
POST http://localhost:8011
content-type: application/json

{
    "jsonrpc": "2.0",
    "id": "2",
    "method": "eth_getBlockTransactionCountByNumber",
    "params": ["0xc9d5bb"]
}

###
POST http://localhost:8011
content-type: application/json

{
    "jsonrpc": "2.0",
    "id": "2",
    "method": "eth_getBlockTransactionCountByNumber",
    "params": ["latest"]
}

###
POST http://localhost:8011
content-type: application/json

{
    "jsonrpc": "2.0",
    "id": "2",
    "method": "eth_getBlockTransactionCountByNumber",
    "params": ["earliest"]
}

###
POST http://localhost:8011
content-type: application/json

{
    "jsonrpc": "2.0",
    "id": "2",
    "method": "hardhat_setBalance",
    "params": [
        "0x36615Cf349d7F6344891B1e7CA7C72883F5dc049",
        "0x1337"
    ]
}

###
POST http://localhost:8011
content-type: application/json

{
    "jsonrpc": "2.0",
    "id": "2",
    "method": "hardhat_setNonce",
    "params": [
        "0x36615Cf349d7F6344891B1e7CA7C72883F5dc049",
        "0x56"
    ]
}

###
POST http://localhost:8011
content-type: application/json

{
    "jsonrpc": "2.0",
    "id": "2",
    "method": "hardhat_mine",
    "params": [
        "0xaa",
        "0x100"
    ]
}

###
POST http://localhost:8011
content-type: application/json

{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "zks_getTokenPrice",
    "params": ["0x0000000000000000000000000000000000000000"]
}

###
POST http://localhost:8011
content-type: application/json

{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "eth_feeHistory",
    "params": ["0x1", "latest", [25, 50 , 75]]
}