name: checks

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  # ensures proper formatting and clippy lint
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install latest nightly
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: rustfmt, clippy

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Run Linters
        run: |
          cargo fmt --all -- --check &&
          cargo clippy -Zunstable-options -- -D warnings --allow clippy::unwrap_used

  # ensures build is successful
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Build Code
        run: make all

      - name: Create artifact
        run: |
          cd ./target/release
          tar -czf era_test_node-${{ matrix.os }}.tar.gz ./era_test_node*

      - name:  Upload artifact
        uses:  actions/upload-artifact@v3
        with:
          name: era_test_node-${{ matrix.os }}.tar.gz
          path: ./target/release/era_test_node-${{ matrix.os }}.tar.gz
  e2e:
    needs: build
    uses: ./.github/workflows/e2e.yml
    name: e2e-tests